# Generated by Django 4.1.5 on 2023-01-05 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 5, 15, 37, 8, 855349), null=None),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='magazine_title')),
                ('publish_year', models.DateField(verbose_name='publish_year')),
                ('pages', models.IntegerField(verbose_name='magazine_page')),
                ('price', models.IntegerField(verbose_name='magazine_price')),
                ('issue', models.CharField(max_length=30, null=True, verbose_name='issue')),
                ('magazine_author', models.ManyToManyField(to='bookshelf.author')),
                ('magazine_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.language')),
            ],
        ),
    ]
