# Generated by Django 4.1.5 on 2023-01-05 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_alter_book_date_published_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 5, 15, 38, 31, 309544), null=None),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Podcast_title')),
                ('publish_year', models.DateField(verbose_name='publish_year')),
                ('time', models.TimeField(verbose_name='Podcast_time')),
                ('price', models.IntegerField(verbose_name='Podcast_price')),
                ('podcast_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.language')),
                ('podcast_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.speaker')),
            ],
        ),
    ]
