# Generated by Django 4.1.5 on 2023-01-05 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_alter_book_date_published_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 5, 15, 43, 32, 840007), null=None),
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Audiobook_title')),
                ('publish_year', models.DateField(null=True, verbose_name='publish_year')),
                ('pages', models.IntegerField(default=0)),
                ('audiobooktime', models.TimeField(default=0, verbose_name='Audiobook_time')),
                ('audiobookprice', models.IntegerField(default=0, verbose_name='Audiobook_price')),
                ('audiobook_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author')),
                ('audiobook_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_language', to='bookshelf.language')),
                ('audiobook_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.speaker')),
                ('audiobook_speaker_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_speaker_language', to='bookshelf.language')),
            ],
        ),
    ]
