# Generated by Django 4.1.5 on 2023-01-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_alter_book_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
    ]
