# Generated by Django 4.1.5 on 2023-01-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_bookreader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookreader',
        ),
    ]
