# Generated by Django 4.1.5 on 2023-01-06 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreader',
            name='start_reading',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 14, 12, 52, 806538)),
        ),
    ]
