# Generated by Django 4.1.5 on 2023-01-06 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo'),
        ('bookshelf', '0012_delete_bookreader'),
        ('libraryclient', '0004_alter_bookreader_start_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('u', 'unread'), ('r', 'reading'), ('f', 'finished')], max_length=5)),
                ('read_pages', models.IntegerField(default=0)),
                ('start_reading', models.DateTimeField(default=datetime.datetime(2023, 1, 6, 14, 52, 5, 182848))),
                ('audiobook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_read', to='bookshelf.audiobook')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_read', to='bookshelf.book')),
                ('magazin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_read', to='bookshelf.magazine')),
                ('podcast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_read', to='bookshelf.podcast')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_read', to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookreader',
        ),
    ]
