# Generated by Django 4.1.5 on 2023-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='user_name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
