# Generated by Django 4.1.5 on 2023-01-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='mobile')),
                ('first_name', models.CharField(max_length=35, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=55, verbose_name='last_name')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=10, verbose_name='gender')),
                ('address', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='Photos/User/unknownen.png', upload_to='Photos/User')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
